name: SocialCredit
version: '1.0'
main: com.array64.socialCredit.SocialCredit
api-version: '1.21'
load: POSTWORLD
authors: [ Array64 ]
description: Social credit system
softdepend: [LuckPerms]
provides:
  - SocialCreditSystem

commands:
  scs:
    description: A command interface for the Social Credit System
    usage: Check /scs help for usage.

permissions:
  socialcreditsystem.fullaccess:
    description: Gives full access to the Social Credit System (through commands)
    default: op
